apiVersion: v1
kind: Service
metadata:
  name: my-angular-docker
spec:
  selector:
    app: my-angular-docker
  type: LoadBalancer
  ports:
    - name: angular-docker-port
      protocol: TCP
      port: 4200
      targetPort: 4200
  externalIPs:
    - 192.168.4.100
  loadBalancerIP: 192.168.0.209
